name: Generate Executables for Tag
on:
    release:
        types:
            - published

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                include:
                    - os: ubuntu-latest
                      artifact_name: ilias-exercise-reminder_linux
                      artifact_ending: .elf
                    - os: windows-latest
                      artifact_ending: .exe
                      artifact_name: ilias-exercise-reminder_win
        steps:
            - name: Get the tag version
              id: get_version
              shell: bash
              run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 14.15.3
            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
            - name: Restore Cached dependencies
              uses: actions/cache@v2
              id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-
            - name: Install dependencies
              run: yarn --immutable
            - name: Build executable
              run: yarn build --target node14-${{ os.runner }}-x64
              env:
                  VERSION: ${{ steps.get_version.outputs.VERSION }}
            - name: Upload executable as artifact
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ matrix.artifact_name }}-${{ steps.get_version.outputs.VERSION }}${{ matrix.artifact_ending }}
                  path: dist/ilias-exercise-reminder-${{ runner.os }}*
            - name: Attach executable to release
              uses: svenstaro/upload-release-action@2.2.1
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: dist/ilias-exercise-reminder-${{ runner.os }}*
                  asset_name: ${{ matrix.artifact_name }}-${{ steps.get_version.outputs.VERSION }}${{ matrix.artifact_ending }}
                  tag: ${{ github.ref }}
